/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package google.form;

public class App {
    public void  getGreeting() {
         // This is to remove unnecessary warnings from your console
         System.setProperty("java.util.logging.config.file", "logging.properties");
        
         TestCases tests = new TestCases(); // Initialize your test class
 
         //TODO: call your test case functions one after other here
 
         tests.testCase01();
 
         //END Tests
 
 
         tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) {
        new App().getGreeting();
    }
}
